version: "3.5"
services:
  php:
    build: ./docker/php
    container_name: design-patterns-php
    volumes:
      - ./project:/srv
  nginx:
    build: ./docker/nginx
    container_name: desing-patterns-nginx
    ports:
      - 80:80
    depends_on:
      - php
